import { SPRITE_PATH } from './config';
import type { Region } from './sprite';

const ms = (value: number) => Number(value.toFixed(2));

/** Source of src/features/sound/sprite.ts: the sprite URL and where every sound sits in it. */
export function spriteModule(regions: [name: string, region: Region][], version: string) {
  const entries = regions.map(
    ([name, { start, duration }]) => `  ${name}: { start: ${ms(start)}, duration: ${ms(duration)} },`,
  );
  return [
    '// Generated by scripts/sounds/generate.ts. Do not edit by hand, run npm run sounds instead.',
    "import type { SoundName } from './types';",
    '',
    'export interface SpriteRegion {',
    '  /** Offset into the decoded sprite, in ms. */',
    '  start: number;',
    '  /** Length in ms. */',
    '  duration: number;',
    '}',
    '',
    '/** Versioned by content, so a rebuilt sprite is never served from a stale cache. */',
    `export const SPRITE_URL = '${SPRITE_PATH}?v=${version}';`,
    '',
    'export const SPRITE_REGIONS: Record<SoundName, SpriteRegion> = {',
    ...entries,
    '};',
    '',
  ].join('\n');
}
