// Generated by scripts/sounds/generate.ts. Do not edit by hand, run npm run sounds instead.

/** Versioned by content, so a rebuilt track is never served from a stale cache. */
export const MUSIC_URL = '/audio/music.mp3?v=7caa09de06';

/** The seamless lap inside the decoded file, in ms. The player loops exactly this span. */
export const MUSIC_LOOP = { start: 84.531, duration: 101052.63 };
