// Generated by scripts/sounds/generate.ts. Do not edit by hand, run npm run sounds instead.
import type { SoundName } from './types';

export interface SpriteRegion {
  /** Offset into the decoded sprite, in ms. */
  start: number;
  /** Length in ms. */
  duration: number;
}

/** Versioned by content, so a rebuilt sprite is never served from a stale cache. */
export const SPRITE_URL = '/audio/sprite.mp3?v=48d4dba05f';

export const SPRITE_REGIONS: Record<SoundName, SpriteRegion> = {
  tab: { start: 112.06, duration: 93 },
  dot: { start: 372.06, duration: 193 },
  toggle: { start: 732.06, duration: 153 },
  blip: { start: 1052.06, duration: 333 },
  move: { start: 1552.06, duration: 203 },
  hover: { start: 1922.06, duration: 56.99 },
};
