// Generated by scripts/sounds/generate.ts. Do not edit by hand, run npm run sounds instead.
import type { LoopName, SoundName } from './types';

export interface SpriteRegion {
  /** Offset into the decoded sprite, in ms. */
  start: number;
  /** Length in ms. */
  duration: number;
  loop: boolean;
}

/** Versioned by content, so a rebuilt sprite is never served from a stale cache. */
export const SPRITE_URL = '/audio/sprite.mp3?v=6d6511c73d';

export const SPRITE_REGIONS: Record<SoundName | LoopName, SpriteRegion> = {
  tick: { start: 112.06, duration: 66.99, loop: false },
  hover: { start: 346.05, duration: 56.99, loop: false },
  tab: { start: 570.04, duration: 93, loop: false },
  toggle: { start: 830.04, duration: 153, loop: false },
  dot: { start: 1150.04, duration: 193, loop: false },
  blip: { start: 1510.04, duration: 333, loop: false },
  focus: { start: 2010.04, duration: 513, loop: false },
  swish: { start: 2690.04, duration: 453, loop: false },
  desk: { start: 3373.04, duration: 8000, loop: true },
  room: { start: 11673.04, duration: 7000, loop: true },
};
