import { DECODER_DELAY, MUSIC_CODED_RATE, MUSIC_PAD } from '../config';
import { padLoop } from '../dsp/loop';
import { SAMPLE_RATE, toSamples } from '../dsp/signal';
import { toMs, type Region } from '../sprite';
import type { Stereo } from './mixdown';

export interface MusicLayout {
  /** The lap as it goes into the file, with a wraparound copy on each side. */
  file: Stereo;
  /** First sample of the lap itself in the file. */
  start: number;
  /** Where the seamless lap sits once decoded, in ms. */
  region: Region;
}

/** The music's decoder delay, in samples at the render rate. */
export const MUSIC_DELAY = (DECODER_DELAY * SAMPLE_RATE) / MUSIC_CODED_RATE;

/** Pads the lap for the file and works out the loop region the player uses. */
export function layoutMusic(lap: Stereo): MusicLayout {
  const start = toSamples(MUSIC_PAD);
  return {
    file: lap.map((signal) => padLoop(signal, MUSIC_PAD)) as Stereo,
    start,
    region: { start: toMs(start + MUSIC_DELAY), duration: toMs(lap[0].length) },
  };
}

const ms = (value: number) => Number(value.toFixed(3));

/** Source of src/features/sound/musicTrack.ts: the music URL and its seamless loop region. */
export function musicModule(path: string, region: Region, version: string) {
  return [
    '// Generated by scripts/sounds/generate.ts. Do not edit by hand, run npm run sounds instead.',
    '',
    '/** Versioned by content, so a rebuilt track is never served from a stale cache. */',
    `export const MUSIC_URL = '${path}?v=${version}';`,
    '',
    '/** The seamless lap inside the decoded file, in ms. The player loops exactly this span. */',
    `export const MUSIC_LOOP = { start: ${ms(region.start)}, duration: ${ms(region.duration)} };`,
    '',
  ].join('\n');
}
